# Titanic Survival Prediction with Logistic Regression

This project predicts whether a passenger survived the Titanic disaster using machine learning.

## 1. Import Libraries

We import NumPy and Pandas for data handling, Seaborn for the Titanic dataset, Matplotlib for visualization, and warning controls.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## 2. Load the Dataset

The Titanic dataset is loaded from Seaborn. Each row represents one passenger.

In [3]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## 3. Explore the Dataset

We inspect the column names, data types, and missing values before preparing the data.

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 100.4 KB

In [6]:
df.drop(['deck', 'embark_town','alive','class', 'who', 'adult_male'], axis = 1, inplace = True)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    str
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    str
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 61.8 KB

## 4. Data Preprocessing

Unnecessary columns are removed. Missing ages are replaced with the average age, and rows with missing embarkation values are removed.

In [8]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
alone         0
dtype: int64

In [9]:
df["age"] = df["age"].fillna(df["age"].median(), inplace = True)

it select the age colomn and replace all its null values with the mean of age column

In [10]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    2
alone       0
dtype: int64

In [11]:
# --- Remove duplicate rows ---
df.columns = df.columns.str.strip()
df_clean = df.drop_duplicates().reset_index(drop=True)

# Check columns
print(df_clean.columns.tolist())

# --- If you want to reset the index after dropping ---
df = df_clean.reset_index(drop=True)

['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'alone']

In [12]:
df.dropna(subset=["embarked"], inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 773 entries, 0 to 774
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  773 non-null    int64
 1   pclass    773 non-null    int64
 2   sex       773 non-null    str
 3   age       773 non-null    float64
 4   sibsp     773 non-null    int64
 5   parch     773 non-null    int64
 6   fare      773 non-null    float64
 7   embarked  773 non-null    str
 8   alone     773 non-null    bool
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 59.6 KB

## 5. Convert Text into Numbers

Machine-learning models require numerical input. Therefore, the `sex` and `embarked` columns are converted into numerical labels.

In [14]:
import sklearn.preprocessing
le = sklearn.preprocessing.LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked']) # S=2, C=0, Q=1

In [15]:
# Truncate/round first, then cast to nullable integer
df = df.round().astype('Int64')

In [16]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     8         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
770         0       3    0   39      0      5    29         1      0
771         1       1    0   19      0      0    30         2      1
772         0       3    0   28      1      2    23         2      0
773         1       1    1   26      0      0    30         0      1
774         0       3    1   32      0      0     8         1      1

[773 rows x 9 columns]

## 6. Separate Features and Target

`X` contains the passenger information used for prediction.  
`y` contains the target value:

- `0` = Did not survive
- `1` = Survived

In [17]:
x = df.drop('survived', axis = 1)
y = df['survived']

## 7. Split the Dataset

The data is divided into training and testing sets. The model learns from the training data and is evaluated on unseen test data.

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

## 8. Train the Logistic Regression Model

Logistic Regression is a classification algorithm used to predict one of two outcomes: survived or did not survive.

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# 1. Fill NaNs using median of each feature
imputer = SimpleImputer(strategy='median')
x_train_imputed = imputer.fit_transform(x_train)
x_test_imputed = imputer.transform(x_test)

# 2. Fit model
model = LogisticRegression(max_iter=1000)
model.fit(x_train_imputed, y_train)

LogisticRegression(max_iter=1000)

## 9. Make Predictions

The trained model predicts survival outcomes for passengers in the test dataset.

In [20]:
y_pred = model.predict(x_test)

In [21]:
y_pred

array([1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       0., 0.])

In [22]:
y_test

364    1
680    1
516    0
169    0
731    1
      ..
55     0
755    1
361    0
539    0
376    1
Name: survived, Length: 155, dtype: Int64

## 10. Evaluate the Model

Accuracy shows the percentage of correct predictions. The confusion matrix and classification report provide additional performance details.

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [24]:
accuracy_score(y_test, y_pred)

0.8258064516129032

In [25]:
confusion_matrix(y_test, y_pred)

array([[69,  9],
       [18, 59]])

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.79      0.88      0.84        78
         1.0       0.87      0.77      0.81        77

    accuracy                           0.83       155
   macro avg       0.83      0.83      0.83       155
weighted avg       0.83      0.83      0.83       155

--------------

### Model based on Naive Bayes Classifier

In [27]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(x_train, y_train)

GaussianNB()

In [28]:
y_pred_NB = model_NB.predict(x_test)

In [29]:
y_pred_NB

array([0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0.,
       1., 0.])

In [30]:
y_test

364    1
680    1
516    0
169    0
731    1
      ..
55     0
755    1
361    0
539    0
376    1
Name: survived, Length: 155, dtype: Int64

### evalute the Model

In [31]:
model_NB.score(x_test, y_test)

0.7612903225806451

In [32]:
accuracy_score(y_test, y_pred_NB)

0.7612903225806451

In [33]:
confusion_matrix(y_test, y_pred_NB)

array([[70,  8],
       [29, 48]])

In [34]:
print(classification_report(y_test, y_pred_NB ))

              precision    recall  f1-score   support

         0.0       0.71      0.90      0.79        78
         1.0       0.86      0.62      0.72        77

    accuracy                           0.76       155
   macro avg       0.78      0.76      0.76       155
weighted avg       0.78      0.76      0.76       155

---

## Model based on Decision Tree Classifier

In [35]:
from sklearn.preprocessing import StandardScaler    
scaler = StandardScaler()
        
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [36]:
# from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier(random_state=42)
# scores = cross_val_score(model_DT, x, y, cv = 10)
# print(scores)
# print(scores.mean())                        
model_DT.fit(x_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [37]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [38]:
accuracy_score(y_test, y_pred_DT)

0.7290322580645161

In [39]:
confusion_matrix(y_test, y_pred_DT)

array([[54, 24],
       [18, 59]])

In [40]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

         0.0       0.75      0.69      0.72        78
         1.0       0.71      0.77      0.74        77

    accuracy                           0.73       155
   macro avg       0.73      0.73      0.73       155
weighted avg       0.73      0.73      0.73       155

----

## SVM Model

### import svm model

In [41]:
from sklearn.svm import SVC
model_SVC = SVC()
model_SVC.fit(x_train_scaled, y_train)

SVC()

In [42]:
y_pred_SVC = model_SVC.predict(x_test_scaled)

In [43]:
accuracy_score(y_test, y_pred_SVC)

0.8258064516129032

In [44]:
confusion_matrix(y_test, y_pred_SVC)

array([[76,  2],
       [25, 52]])

In [45]:
print(classification_report(y_test, y_pred_SVC))

              precision    recall  f1-score   support

         0.0       0.75      0.97      0.85        78
         1.0       0.96      0.68      0.79        77

    accuracy                           0.83       155
   macro avg       0.86      0.82      0.82       155
weighted avg       0.86      0.83      0.82       155

---

## cross validation

In [46]:
x

     pclass  sex  age  sibsp  parch  fare  embarked  alone
0         3    1   22      1      0     7         2      0
1         1    0   38      1      0    71         0      0
2         3    0   26      0      0     8         2      1
3         1    0   35      1      0    53         2      0
4         3    1   35      0      0     8         2      1
..      ...  ...  ...    ...    ...   ...       ...    ...
770       3    0   39      0      5    29         1      0
771       1    0   19      0      0    30         2      1
772       3    0   28      1      2    23         2      0
773       1    1   26      0      0    30         0      1
774       3    1   32      0      0     8         1      1

[773 rows x 8 columns]

In [47]:
from sklearn.model_selection import cross_val_score

In [48]:
scaler = StandardScaler()   # scaler object used to standardize the data 
# for example: x = scaler.fit_transform(x) transforms the data like x = (x - mean(x)) / std(x)  
x_scaled = scaler.fit_transform(x)

In [49]:
x_scaled

array([[ 0.88090573,  0.77486391, -0.54825479, ..., -0.52995073,
         0.59027897, -1.1344524 ],
       [-1.46716368, -1.2905492 ,  0.61783553, ...,  0.6915804 ,
        -1.8895343 , -1.1344524 ],
       [ 0.88090573, -1.2905492 , -0.25673221, ..., -0.51086431,
         0.59027897,  0.88148255],
       ...,
       [ 0.88090573, -1.2905492 , -0.11097092, ..., -0.22456795,
         0.59027897, -1.1344524 ],
       [-1.46716368,  0.77486391, -0.25673221, ..., -0.09096298,
        -1.8895343 ,  0.88148255],
       [ 0.88090573,  0.77486391,  0.18055166, ..., -0.51086431,
        -0.64962767,  0.88148255]], shape=(773, 8))

In [50]:
scores = cross_val_score(model_SVC, x_scaled, y, cv = 10, scoring='accuracy')

In [51]:
print(scores)
print(scores.mean())

[0.78205128 0.80769231 0.75641026 0.84415584 0.79220779 0.79220779
 0.80519481 0.75324675 0.90909091 0.84415584]
0.8086413586413587

In [52]:
print(scores.std())

0.04435003462029847